CREATE TABLE IF NOT EXISTS Users (
  UserID VARCHAR(32) NOT NULL PRIMARY KEY,
  Rating INT UNSIGNED NOT NULL,
  Location VARCHAR(128),
  Country VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS Items (
  ItemID INT UNSIGNED NOT NULL PRIMARY KEY,
  Name VARCHAR(128) NOT NULL,
  Currently DECIMAL(8,2) NOT NULL,
  Buy_Price DECIMAL(8,2) NULL,
  First_Bid DECIMAL(8,2) NOT NULL,
  Number_of_Bids  INT NOT NULL,
  Latitude VARCHAR(64) NULL,
  Longitude VARCHAR(64) NULL,
  Location VARCHAR(128) NULL,
  Country VARCHAR(64),
  Started TIMESTAMP NOT NULL,
  Ends TIMESTAMP NOT NULL,
  SellerID VARCHAR(32) NOT NULL,
  Description VARCHAR(4000),
  FOREIGN KEY (SellerID) REFERENCES
    Users(UserID)
      ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ItemCategories (
  Category VARCHAR(256) NOT NULL,
  ItemID INT UNSIGNED NOT NULL,
  FOREIGN KEY(ItemID) REFERENCES
    Items(ItemID)
      ON DELETE CASCADE,
  UNIQUE KEY `category_item` (Category,ItemID)
);

CREATE TABLE IF NOT EXISTS Bids (
  UserID VARCHAR(32) NOT NULL PRIMARY KEY,
  Time TIMESTAMP NOT NULL,
  ItemID INT UNSIGNED NOT NULL,
  Amount DECIMAL(8,2) NOT NULL,
  FOREIGN KEY(ItemID) REFERENCES
    Items(ItemID)
      ON DELETE CASCADE,
  FOREIGN KEY(UserID) REFERENCES
    Users(UserID)
      ON DELETE CASCADE,
  UNIQUE KEY `bid_time` (UserID, Time)
);